# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'AlexMac250'

branding:
    icon: 'check'
    color: 'blue'

description: 'Use PHP-CS-Fixer via GithubAction.'

name: 'OSKAR-PHP-CS-Fixer'

runs:
    using: 'docker'
    image: 'docker://alexmac250/php-cs-fixer-ga:3.67.1'
